providers:
  cloudflare:
    class: octodns.provider.cloudflare.CloudflareProvider
    token: env/CLOUDFLARE_API_TOKEN

zones:
  co2028.com.:
    sources:
      - config
    targets:
      - cloudflare

