---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./
    enforce_order: False
  cloudflare:
    class: octodns_cloudflare.CloudflareProvider
    #    email: env/CLOUDFLARE_EMAIL
    token: env/CLOUDFLARE_TOKEN
    # account_id: env/CLOUDFLARE_ACCOUNT_ID

zones:
  co2028.com.:
    sources:
      - config
    targets:
      - cloudflare
    
