name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  octodns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3'
      - name: Install OctoDNS
        run: pip install 'octodns==0.9.10'
      - name: Install OctoDNS-Cloudflare
        run: pip install octodns-cloudflare
      - name: Sync w/ production DNS providers
        run: ./bin/sync
        env:
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
