name: Deploy DNS with OctoDNS

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install OctoDNS Cloudflare
        run: pip install octodns-cloudflare
        
      - name: Install OctoDNS
        run: pip install octodns

      - name: Sync DNS with OctoDNS
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          octodns-sync --config-file=config.yaml

